### ISSUE TITLE
is there any way to add numbering code editor 

### ISSUE THREAD

**Issue by satyapsr13** [CodoPixel/code_editor#11]

**Comment by ThomasGysemans** [comment]
What do you mean with "numbering" ? Do you mean several code editors on a same page?

**Comment by satyapsr13** [comment]
no i  mean 
![image](https://user-images.githubusercontent.com/73766765/142618385-b1bd5469-a99e-4d15-bcf5-360240f955c1.png)

**Comment by ThomasGysemans** [comment]
It is not possible, I will add that in the future, but I'm very busy right now, sorry

**Comment by ThomasGysemans** [comment]
Hi, sorry for the huge break I took from this package. I'm sorry to announce that I will not be adding such numbering system because my package isn't meant to contain files with a big number of lines.
