### ISSUE TITLE
How this editor know this was class, variable and function etc. for perticular language

### ISSUE THREAD

**Issue by CodeWithNav** [CodoPixel/code_editor#14]

**Comment by ThomasGysemans** [comment]
Hi, your question isn't very clear... If you're wondering how the syntax highlighting manages to recognize what's a class, a variable or a function from plain text, then I'll have to say that it depends. It depends on the way the abstract tree is generated.

I'm not responsible of that part. I use this package for the syntax highlighting: [flutter_highlight](https://pub.dev/packages/flutter_highlight).

Maybe you could find interesting info here on a [Abstract Syntax Tree](https://en.wikipedia.org/wiki/Abstract_syntax_tree)
