### ISSUE TITLE
NullSafety Missing

### ISSUE THREAD

**Issue by rohitranjan1991** [CodoPixel/code_editor#5]
Cam you please add Null Safety.

**Comment by aadarshadhakalg** [comment]
Hey, I have create a PR #4 , the maintainer might be working on it. Till then you can use it from my forked repo. Just add these lines in pubspec.yaml

```
code_editor:
  git:
    url: https://github.com/aadarshadhakalg/code_editor.git
```

**Comment by jwafu** [comment]
@aadarshadhakalg this has been updated

**Comment by aadarshadhakalg** [comment]
Yeah. I think this issue can now be closed. @CodoPixel

**Comment by ThomasGysemans** [comment]
Thanks again
